[project]
name = "gruner-ai-features"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx>=0.26.0",
    "python-multipart",
    "python-dotenv",
    "groq",
    "qdrant-client>=1.8.0",
    "librosa>=0.11.0",
    "sentencepiece>=0.2.1",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "transformers>=4.57.0",
    "torchcodec>=0.10.0",
    "python-docx>=1.2.0",
    "docx2txt>=0.9",
    "docling>=2.75.0",
    "redis>=7.2.0",
    "strands-agents[openai]==1.29.0",
    "psycopg2-binary>=2.9.11",
    "edge-tts>=6.1.0",
    "python-socketio>=5.16.1",
    "aws-sdk-bedrock-runtime>=0.4.0",
]
